### ISSUE TITLE
Non-alphabet characters are being dropped

### ISSUE THREAD

**Issue by jerryjohnjacob** [Amitaajay/Cipher-text#1]
Any non-alphabetic character like numbers, whitespaces and punctuation are simply getting dropped, which is not ideal.

<img width="312" alt="Screenshot 2020-09-29 at 3 45 29 PM" src="https://user-images.githubusercontent.com/4962432/94548393-460f5480-026e-11eb-8530-90386ce68d53.png">

Please add a fix for this.

**Comment by Amitaajay** [comment]
I have made the necessary corrections for it.
