### ISSUE TITLE
Expectation to provide message within quotation marks

### ISSUE THREAD

**Issue by jerryjohnjacob** [Amitaajay/Cipher-text#2]
It took me a moment to figure out why strings I was entering were getting rejected:

<img width="393" alt="Screenshot 2020-09-29 at 3 46 06 PM" src="https://user-images.githubusercontent.com/4962432/94548527-7f47c480-026e-11eb-8a27-b3fc7cd72baf.png">

Please add a fix for this.

**Comment by Amitaajay** [comment]
I did the program in python 3 actually. I have made some corrections. It should work in both now.
